### ISSUE TITLE
Project inclusions

### ISSUE THREAD

**Issue by visbook** [wilgaboury/super-speedy-dial#5]
Hi Wil
Have you heard of an old similar add-on called ViewMarks by Michael Koch?
https://www.maketecheasier.com/organize-firefox-bookmarks-with-viewmarks/

It was a great visual bookmarking add-on that also used folders but unfortunately stopped working properly after FF57 and Michael has abandoned it.

It was very easy to use...right click the webpage and save into one of your category folders; it saved a thumbnail of the whole webpage and made saving a visual record of webpages for future research, shopping, interests, pages to revisit, etc, so simple; and having a visual representation of the whole webpage made it easy to recall what the bookmark was about.

I'm not a programmer, so don't know how easy it would be to implement some of the features of ViewMarks, but I (and sure many others) have been waiting for an add-on with its capabilities and maybe yours could be the one!

![Classics Archive](https://user-images.githubusercontent.com/87253369/125182061-1c984600-e24e-11eb-8715-47cfb13def00.jpg)
![ViewMarks](https://user-images.githubusercontent.com/87253369/125182065-23bf5400-e24e-11eb-9c1b-d1473c1c683f.jpg)

If you install Waterfox Classic it can run old add-ons

**Comment by metsci-gaboury** [comment]
I'm a single developer working on this in my free time for personal use. I'm sorry to say while I find some of these features interesting that I don't see myself implementing any of them in the foreseeable future. The web extensions api that my plugin uses for interfacing with firefox bookmarks is somewhat limited in what it can do, which would make some of these things a technical challenge.

**Comment by wilgaboury** [comment]
I'm a single developer working on this in my free time for personal use. I'm sorry to say while I find some of these features interesting that I don't see myself implementing any of them in the foreseeable future. The web extensions api that my plugin uses for interfacing with firefox bookmarks is somewhat limited in what it can do, which would make some of these things a technical challenge. When I have some free time I'll download waterfox classic or palemoon and try this extension out, maybe I'll get some inpriration from it.
